#!/usr/bin/env python3
"""
Solver adapters for the rigging optimization study.

Two implementations behind one interface:

  SU2Runner    - writes an SU2 config, runs SU2_CFD, parses forces from
                 history.csv. This is the real thing.
  DummyRunner  - an analytic stand-in with no CFD at all. Exists so the
                 OPTIMIZER HARNESS can be tested end to end - DOE, screening,
                 refinement, checkpointing, feasibility rejection - without
                 burning CFD runs or waiting for a solver. Every bug in the
                 harness is a bug you want to find in 2 seconds, not 6 hours
                 into a DOE.

  Interface:  run(mesh_file, case_dir, v_inf, ref_chord) -> dict

SIGN CONVENTION - READ THIS
---------------------------
mesh_section.py mirrors the stack into CAR orientation: suction side faces the
ground, so the wing pushes DOWN. SU2 reports CL in the standard sense (positive
= up), so a working front wing returns a NEGATIVE CL.

    downforce coefficient  =  -CL_su2

Both runners return `cl_down` (positive = downforce, which is what you want)
alongside the raw `cl`. Optimize on cl_down. Getting this backwards produces a
study that carefully maximizes lift.

WHAT I HAVE NOT VERIFIED
------------------------
I could not run SU2 while writing this: it is not installed in the environment
this was developed in. The harness is fully tested against DummyRunner, but the
SU2 config below is written from the documentation, not from a run that
converged. SU2 config keys also drift between major versions.

    ==> RUN ONE CASE BY HAND BEFORE LAUNCHING A DOE. <==

    python optimize.py --baseline

Check that it converges, that the forces are physically sane, and that CL is
negative. Only then let the optimizer loose on 30 of them. Never spend a DOE
budget on an unvalidated solver setup.
"""

import csv
import os
import shutil
import subprocess

import numpy as np

RHO = 1.225                 # sea-level density [kg/m^3]
MU = 1.789e-5               # dynamic viscosity [Pa s]


# ---------------------------------------------------------------------------
# SU2
# ---------------------------------------------------------------------------
SU2_CFG = """\
% Front-wing outboard stack, 2-D incompressible RANS in ground effect.
% Generated by solvers.py - do not hand-edit; edit the template instead.

% ---------------- PROBLEM ----------------
% INC_RANS, not RANS: at 20-27 m/s the Mach number is ~0.06-0.08. A
% compressible solver at M<0.1 is stiff and converges badly. Incompressible is
% both faster and better conditioned here.
SOLVER= INC_RANS
KIND_TURB_MODEL= SST
{transition}
MATH_PROBLEM= DIRECT
RESTART_SOL= NO

% ---------------- FREESTREAM ----------------
INC_DENSITY_MODEL= CONSTANT
INC_ENERGY_EQUATION= NO
INC_DENSITY_INIT= {rho}
INC_VELOCITY_INIT= ( {v}, 0.0, 0.0 )
INC_NONDIM= DIMENSIONAL
VISCOSITY_MODEL= CONSTANT_VISCOSITY
MU_CONSTANT= {mu}

% Freestream turbulence. n_crit 6 in the screen corresponds to a moderately
% turbulent outdoor flow; 1% intensity is the matching RANS assumption.
FREESTREAM_TURBULENCEINTENSITY= 0.01
FREESTREAM_TURB2LAMVISCRATIO= 10.0

% ---------------- REFERENCE VALUES ----------------
% 2-D: reference "area" is the chord x 1 m of span.
REF_AREA= {ref_chord}
REF_LENGTH= {ref_chord}
REF_ORIGIN_MOMENT_X= 0.0
REF_ORIGIN_MOMENT_Y= 0.0
REF_ORIGIN_MOMENT_Z= 0.0
% AOA is ZERO: incidence is baked into the rigged geometry, not applied here.
AOA= 0.0

% ---------------- BOUNDARY CONDITIONS ----------------
% Marker names come from mesh_section.py and are already in the .su2 file.
MARKER_HEATFLUX= ( main, 0.0, flap1, 0.0, flap2, 0.0, ground, 0.0 )
MARKER_FAR= ( inlet, outlet, top )

% THE GROUND IS A MOVING WALL. A stationary ground grows its own boundary
% layer, which is physically wrong (the road moves relative to the car) and
% will corrupt the ground-effect result - the single thing this mesh exists to
% capture.
MARKER_MOVING= ( ground )
SURFACE_MOVEMENT= MOVING_WALL
SURFACE_TRANSLATION_RATE= ( {v}, 0.0, 0.0 )

MARKER_PLOTTING= ( main, flap1, flap2 )
MARKER_MONITORING= ( main, flap1, flap2 )

% ---------------- NUMERICS ----------------
NUM_METHOD_GRAD= GREEN_GAUSS
CFL_NUMBER= 5.0
CFL_ADAPT= YES
CFL_ADAPT_PARAM= ( 0.1, 2.0, 5.0, 100.0 )
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-6
LINEAR_SOLVER_ITER= 10

CONV_NUM_METHOD_FLOW= FDS
MUSCL_FLOW= YES
SLOPE_LIMITER_FLOW= VENKATAKRISHNAN
VENKAT_LIMITER_COEFF= 0.05
TIME_DISCRE_FLOW= EULER_IMPLICIT

CONV_NUM_METHOD_TURB= SCALAR_UPWIND
MUSCL_TURB= NO
TIME_DISCRE_TURB= EULER_IMPLICIT

% ---------------- CONVERGENCE ----------------
ITER= {iters}
CONV_FIELD= RMS_PRESSURE
CONV_RESIDUAL_MINVAL= -8
CONV_STARTITER= 50
% Also stop when the FORCES stop moving - residuals can plateau while the
% coefficients are still drifting, and the coefficients are what we optimize.
WINDOW_CAUCHY_CRIT= YES
CONV_WINDOW_CAUCHY_EPS= 1E-5
CONV_WINDOW_STARTITER= 100
CONV_WINDOW_FIELD= ( DRAG, LIFT )

% ---------------- I/O ----------------
MESH_FILENAME= {mesh}
MESH_FORMAT= SU2
SCREEN_OUTPUT= ( INNER_ITER, RMS_PRESSURE, RMS_TKE, LIFT, DRAG )
HISTORY_OUTPUT= ( ITER, RMS_RES, AERO_COEFF )
CONV_FILENAME= history
OUTPUT_FILES= ( RESTART, PARAVIEW )
VOLUME_FILENAME= flow
SURFACE_FILENAME= surface
OUTPUT_WRT_FREQ= 500
"""


class SU2Runner:
    """Runs SU2_CFD on a mesh and returns forces.

    transition=True switches on the Langtry-Menter transition model. That is
    the physically consistent choice - this whole project rests on transition
    behavior (the screen gates on n_crit 6 with a tripped LE) - but LM is
    stiffer, slower, and needs y+ ~ 1, which the mesh delivers. Start with it
    OFF to get a converging baseline, then turn it on.
    """

    name = "su2"

    def __init__(self, exe="SU2_CFD", iters=3000, transition=False, nproc=1):
        self.exe = exe
        self.iters = iters
        self.transition = transition
        self.nproc = nproc

    def available(self):
        return shutil.which(self.exe) is not None

    def run(self, mesh_file, case_dir, v_inf, ref_chord):
        os.makedirs(case_dir, exist_ok=True)
        mesh_local = os.path.basename(mesh_file)
        shutil.copy(mesh_file, os.path.join(case_dir, mesh_local))

        cfg = SU2_CFG.format(
            rho=RHO, mu=MU, v=v_inf, ref_chord=ref_chord,
            mesh=mesh_local, iters=self.iters,
            transition="KIND_TRANS_MODEL= LM" if self.transition
                       else "% KIND_TRANS_MODEL= LM   (fully turbulent)",
        )
        cfg_path = os.path.join(case_dir, "case.cfg")
        with open(cfg_path, "w") as f:
            f.write(cfg)

        cmd = ([ "mpirun", "-n", str(self.nproc), self.exe, "case.cfg"]
               if self.nproc > 1 else [self.exe, "case.cfg"])
        with open(os.path.join(case_dir, "su2.log"), "w") as log:
            proc = subprocess.run(cmd, cwd=case_dir, stdout=log,
                                  stderr=subprocess.STDOUT)

        res = self._parse_history(os.path.join(case_dir, "history.csv"))
        res["returncode"] = proc.returncode
        res["case_dir"] = case_dir
        if proc.returncode != 0:
            res["converged"] = False
            res["error"] = f"SU2 exited {proc.returncode} - see su2.log"
        return res

    @staticmethod
    def _parse_history(path):
        """Last row of history.csv -> forces. NaN if the run never produced one."""
        bad = dict(cl=np.nan, cd=np.nan, cl_down=np.nan, converged=False,
                   iters=0, error="no history.csv")
        if not os.path.exists(path):
            return bad
        with open(path) as f:
            rows = list(csv.reader(f))
        if len(rows) < 2:
            return bad
        hdr = [h.strip().strip('"') for h in rows[0]]
        last = rows[-1]

        def col(*names):
            for n in names:
                if n in hdr:
                    return float(last[hdr.index(n)])
            return np.nan

        cl = col("CL", "LIFT")
        cd = col("CD", "DRAG")
        return dict(
            cl=cl, cd=cd,
            cl_down=-cl,                 # SIGN: front wing pushes DOWN
            iters=int(col("Inner_Iter", "Iteration") or 0),
            rms=col("rms[P]", "rms[Rho]"),
            converged=bool(np.isfinite(cl) and np.isfinite(cd)),
            error=None,
        )


# ---------------------------------------------------------------------------
# Dummy
# ---------------------------------------------------------------------------
class DummyRunner:
    """Analytic stand-in. NOT physics - a smooth surrogate with the right SHAPE.

    Purpose: exercise the optimizer harness. It has a real optimum, realistic
    interactions between rigging variables, a stall-like penalty when the flaps
    are over-deflected, and ground-effect sensitivity - so screening and
    refinement have something to actually find. Runs in microseconds.

    If the harness cannot find the optimum of THIS, it will not find it in CFD.
    """

    name = "dummy"

    def __init__(self, noise=0.002, seed=0):
        self.rng = np.random.default_rng(seed)
        self.noise = noise

    def available(self):
        return True

    def run(self, mesh_file, case_dir, v_inf, ref_chord, rig=None):
        r = rig or {}
        a = r.get("alpha_main", 3.0)
        d1, d2 = r.get("delta1", 20.0), r.get("delta2", 25.0)
        g1, g2 = r.get("gap1", 0.025), r.get("gap2", 0.025)
        o1, o2 = r.get("overlap1", 0.03), r.get("overlap2", 0.03)
        h = r.get("ride_height", 0.050)

        # circulation grows with incidence + deflection, saturating (stall-like)
        load = (0.06 * a + 0.045 * d1 + 0.030 * d2)
        load -= 0.0012 * max(0.0, d1 - 24) ** 2      # flap1 over-deflection
        load -= 0.0016 * max(0.0, d2 - 30) ** 2      # flap2 over-deflection
        # slots: too tight chokes, too wide leaks. optimum ~0.022 / 0.020
        load -= 55 * (g1 - 0.022) ** 2 + 45 * (g2 - 0.020) ** 2
        load += 0.9 * o1 + 0.6 * o2
        # ground effect: more downforce closer to the ground
        load *= 1.0 + 0.55 * np.exp(-(h - 0.020) / 0.045)

        cd = (0.020 + 0.0022 * a + 0.0016 * d1 + 0.0013 * d2
              + 0.021 * load ** 2                     # induced-ish
              + 0.9 * max(0.0, 0.018 - g1) ** 1.5)    # choked slot -> separation
        cl_down = max(0.05, load)
        cl_down += self.rng.normal(0, self.noise)
        cd += abs(self.rng.normal(0, self.noise * 0.3))
        return dict(cl=-cl_down, cd=cd, cl_down=cl_down, converged=True,
                    iters=1, rms=-9.0, error=None, case_dir=case_dir,
                    returncode=0)


def get_solver(name, **kw):
    if name == "su2":
        return SU2Runner(**kw)
    if name == "dummy":
        return DummyRunner(**{k: v for k, v in kw.items()
                              if k in ("noise", "seed")})
    raise SystemExit(f"unknown solver '{name}' (su2 | dummy)")
